<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Fantactics.Core\Fantactics.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Profiles\Data\*.json" LogicalName="Fantactics.Ai.Profiles.Data.%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
